version: 2.0
jobs:
  initialTest:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          command: python run.py
      - store_test_results:
          path: test-results
  build:
    machine: true
    steps:
      - checkout
    # login to docker:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    
    #build the image
      - run: docker build -t https://github.com/VintherWolf/ca-project/v1.0:$CIRCLE_SHA1 .

    # deploy the image 
      - run: docker push vintherwolf/caproject:$CIRCLE_SHA1

workflows:
  version: 2
  jobSequence:
    jobs:
      - initialTest:
          filters:
            branches:
              only:
                - master
      - build:
          filters:
            branches:
              only: 
                - master
          requires:
            - initialTest