version: 2.0
jobs:
  build:
    machine: true
    steps:
      - checkout
    # login to docker:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    
    #build the image
      - run: docker build -t vintherwolf/ca-project/master:$CIRCLE_SHA1 .

    # deploy the image 
      - run: docker push vintherwolf/caproject:$CIRCLE_SHA1
      
  initialTest:
    docker:
      - image: vintherwolf/caproject:latest
    steps:
      - checkout
      - run:
          command: python run.py
      - store_test_results:
          path: test-results
workflows:
  version: 2
  jobSequence:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
      - initialTest:
          filters:
            branches:
              only:
                - master            